CREATE TABLE IBGE (
    ID     CHAR(7) NOT NULL,
    STATE  CHAR(2),
    CITY   VARCHAR(80)
);

ALTER TABLE IBGE ADD CONSTRAINT PK_IBGE PRIMARY KEY (ID);

CREATE INDEX IX_IBGE_CITY ON IBGE (CITY);
CREATE INDEX IX_IBGE_ID ON IBGE (ID);
CREATE INDEX IX_IBGE_STATE ON IBGE (STATE);
