DROP TABLE IBGE;

CREATE TABLE IBGE (
  id    CHAR(7) NOT NULL,
  State CHAR(2),
  City  VARCHAR(80)  
);

ALTER TABLE IBGE ADD CONSTRAINT PK_IBGE PRIMARY KEY (id);

CREATE INDEX IX_IBGE_City ON IBGE ( City );

CREATE INDEX IX_IBGE_State ON IBGE ( State );
