DROP TABLE IF EXISTS IBGE

CREATE TABLE IF NOT EXISTS IBGE (
	Id      VARCHAR(7) NOT NULL,
	City    VARCHAR(2) NOT NULL,
	State   VARCHAR(80) NOT NULL
);

ALTER TABLE IBGE ADD CONSTRAINT PK_IBGE PRIMARY KEY (Id);

CREATE INDEX IX_IBGE_Id ON IBGE (Id);

CREATE INDEX IX_IBGE_City ON IBGE (City);

CREATE INDEX IX_IBGE_State ON IBGE (State);