DROP TABLE IF EXISTS `ibge`
CREATE TABLE IF NOT EXISTS `ibge` (
	`id` VARCHAR(7) NOT NULL,
	`city` VARCHAR(2) NOT NULL,
	`state` VARCHAR(80) NOT NULL
);
ALTER TABLE `ibge` ADD CONSTRAINT PK_IBGE PRIMARY KEY (`id`);
CREATE INDEX IX_IBGE_Id ON ibge (`id`);
CREATE INDEX IX_IBGE_City ON ibge (`city`);
CREATE INDEX IX_IBGE_State ON ibge (`state`);